
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - dock_net
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - /home/jcuzin/data:/mariaDB/
    networks:
      - dock_net

# volumes:
#   mariaDB:

networks:
  dock_net:
    driver: bridge