
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - dock_net
  mariadb:
    build:
      context: ./mariadb
    networks:
      - dock_net

networks:
  dock_net:
    driver: bridge