
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - dock_net
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - db-mariadb
    networks:
      - dock_net

volumes:
  db-mariadb:

networks:
  dock_net:
    driver: bridge