
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - dock_net
  # wordpress:
  #   build:
  #     context: ./wordpress
  #   volumes:
  #     - /home/jcuzin/data:/wordpress/
  #   networks:
  #     - dock_net
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - /home/jcuzin/data:/mariaDB/
    networks:
      - dock_net
    env_file:
      - .env

networks:
  dock_net:
    driver: bridge